kadi/modules/main/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kadi/modules/main/api/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from . import internal
from . import v1_0

kadi/modules/main/api/internal/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from . import get

kadi/modules/main/api/v1_0/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from . import get

kadi/modules/main/blueprint.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask import Blueprint
from flask import current_app
from flask import render_template
from flask import request
from flask_limiter.errors import RateLimitExceeded
from flask_login import current_user
from flask_wtf.csrf import CSRFError
from werkzeug.exceptions import HTTPException

import kadi.lib.constants as const
from kadi.ext.talisman import talisman
from kadi.lib.api.core import json_error_response
from kadi.lib.api.utils import is_api_request
from kadi.lib.web import get_error_message
from kadi.lib.web import get_locale


bp = Blueprint("main", __name__, template_folder="templates")


@bp.app_errorhandler(HTTPException)
def _app_errorhandler(e):
    # Before returning any error information, we redirect anonymous users using
    # Flask-Login's functionality to get consistent behaviour with actual unauthorized
    # requests. We ignore CSRF-related errors (as this can interfere with the session
    # user loader) as well as rate limit and server errors.
    if (
        not isinstance(e, (CSRFError, RateLimitExceeded))
        and not e.code >= 500
        and not current_user.is_authenticated
    ):
        return current_app.login_manager.unauthorized()

    # If another pre-request handler aborts with an exception, the nonce will never get
    # created, so we call all Flask-Talisman handlers manually again just in case.
    talisman._force_https()
    talisman._make_nonce()

    if isinstance(e, RateLimitExceeded):
        description = f"Rate limit exceeded ({e.description}). Please try again later."
    else:
        description = e.description

    if is_api_request():
        response = json_error_response(
            e.code, message=get_error_message(e.code), description=description
        )
    else:
        template = render_template(
            "main/error.html",
            title=e.code,
            status_code=e.code,
            message=get_error_message(e.code),
            description=description,
        )

        response = current_app.response_class(response=template, status=e.code)

    talisman._set_response_headers(response)
    return response


@bp.after_app_request
def _after_app_request(response):
    if not is_api_request() and request.endpoint != "static":
        response.set_cookie(
            "locale",
            value=get_locale(),
            max_age=365 * const.ONE_DAY,
            samesite="Lax",
            secure=current_app.config["LOCALE_COOKIE_SECURE"],
        )

    return response


from . import views  # pylint: disable=unused-import

kadi/modules/main/views.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask import render_template
from flask_babel import gettext as _
from flask_login import current_user

from .blueprint import bp
from kadi.ext.db import db
from kadi.modules.collections.models import Collection
from kadi.modules.groups.models import Group
from kadi.modules.groups.utils import get_user_groups
from kadi.modules.permissions.core import get_permitted_objects
from kadi.modules.records.models import Record
from kadi.version import __version__


@bp.route("/")
def index():
    """The index/home page.

    Will change depending on whether the current user is authenticated or not.
    """
    if not current_user.is_authenticated:
        return render_template("main/index.html", version=__version__)

    records_query = get_permitted_objects(current_user, "read", "record")
    collections_query = get_permitted_objects(current_user, "read", "collection")

    resource_queries = []
    for model, query, endpoint in [
        (Record, records_query, "records.view_record"),
        (Collection, collections_query, "collections.view_collection"),
    ]:
        resources_query = query.with_entities(
            model.id,
            model.title,
            model.identifier,
            model.plain_description,
            model.visibility,
            model.last_modified.label("last_modified"),
            db.literal(model.__tablename__).label("type"),
            db.literal(endpoint).label("endpoint"),
        ).filter(model.state == "active")

        resource_queries.append(resources_query)

    resources = (
        resource_queries[0]
        .union(*resource_queries[1:])
        .order_by(db.desc("last_modified"))
        .limit(8)
    )

    # No need to filter permitted groups, as the current user will have at least read
    # permission for his own groups.
    paginated_groups = (
        get_user_groups(current_user)
        .order_by(Group.last_modified.desc())
        .paginate(1, 4, False)
    )

    return render_template(
        "main/home.html",
        title=_("Home"),
        groups=paginated_groups.items,
        has_more_groups=paginated_groups.has_next,
        latest_updates=resources.all(),
    )


@bp.route("/about")
def about():
    """The about page."""
    return render_template("main/about.html", title=_("About"), version=__version__)


@bp.route("/help")
def help():
    """The help page."""
    return render_template("main/help.html", title=_("Help"))

kadi/modules/main/templates/main/about.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content %}
  <div class="card">
    <div class="card-header">{% trans %}About{% endtrans %}</div>
    <div class="card-body">
      {{ template_hook("kadi_template_about_before") }}

      <div class="d-flex justify-content-between align-items-end">
        <a href="{% trans %}https://www.kit.edu/english{% endtrans %}" class="mr-5">
          <img class="img-fluid mb-4" src="{{ static_url('images/kit.png') }}" width="140">
        </a>
        <a href="{% trans %}https://www.iam.kit.edu/cms/english{% endtrans %}">
          <img class="img-fluid mb-4" src="{{ static_url('images/iam.png') }}" width="120">
        </a>
      </div>
      <p>
        <strong>Kadi4Mat</strong> is the <strong>Karlsruhe Data Infrastructure for Materials Science</strong>, a
        software for managing research data with the aim of combining new concepts with established technologies and
        existing solutions.
      </p>
      <p>
        The aim of this project is to combine the ability to manage and exchange data (the <em>Repository</em>) with the
        possibility to analyze, visualize and transform said data (the <em>Electronic Lab Notebook</em>). The latter is
        made possible by employing a modular architecture, which allows to cover the specific needs of different
        scientists each utilizing unique workflows, while also opening the possibility to easily branch out into other
        disciplines in the future. Eventually, the goal is to cover the whole scientific workflow of day to day
        research, starting from the creation of data, including interfacing with devices for experimenters, up to the
        publishing of the data as well as corresponding results.
      </p>
      <p>
        Kadi4Mat is being developed as part of several research projects at the
        <a href="{% trans %}https://www.iam.kit.edu/cms/english{% endtrans %}">
          <strong>Institute for Applied Materials - Computational Materials Science (IAM-CMS)</strong>
        </a>
        of the
        <a href="{% trans %}https://www.kit.edu/english{% endtrans %}">
          <strong>Karlsruhe Institute of Technology (KIT).</strong>
        </a>
      </p>
      <hr>
      <strong>More information:</strong>
      <a href="https://kadi.iam-cms.kit.edu">https://kadi.iam-cms.kit.edu</a>
      <br>
      <strong>Source code:</strong>
      <a href="https://gitlab.com/iam-cms/kadi">https://gitlab.com/iam-cms/kadi</a>
      <br>
      <strong>Releases:</strong>
      <a href="https://pypi.org/project/kadi">https://pypi.org/project/kadi</a>
      <br>
      <strong>Developer documentation:</strong>
      <ul class="mb-0">
        <li>
          <strong>Latest</strong> (reflecting the <em>master</em> branch):
          <a href="https://kadi4mat.readthedocs.io/en/latest">https://kadi4mat.readthedocs.io/en/latest</a>
        </li>
        <li>
          <strong>Stable</strong> (reflecting the latest release):
          <a href="https://kadi4mat.readthedocs.io/en/stable">https://kadi4mat.readthedocs.io/en/stable</a>
        </li>
      </ul>

      {{ template_hook("kadi_template_about_after") }}
    </div>

    <div class="card-footer">
      <small class="badge border border-muted font-weight-normal text-muted">Kadi4Mat v{{ version }}</small>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/error.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content_wrapper %}
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <h1 class="text-center">{{ status_code }}</h1>
      <h5 class="text-center">{{ message }}</h5>
      <p class="text-center">{{ description }}</p>
      <p class="text-center">
        <a href="{{ url_for('main.index') }}">
          <strong>{% trans %}Return to the homepage.{% endtrans %}</strong>
        </a>
      </p>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/help.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content %}
  <div class="card">
    <div class="card-header">{% trans %}Help{% endtrans %}</div>
    <div class="row">
      <div class="d-none d-lg-block col-lg-4 col-xl-3">
        <nav id="help-navbar" class="navbar flex-column bg-light overflow-auto" style="height: 75vh;">
          <nav class="nav nav-pills flex-column">
            {{ template_hook("kadi_template_help_nav_before") }}

            <a class="nav-link my-1" href="#login">
              <strong>Logging in</strong>
            </a>
            <a class="nav-link my-1" href="#navigation">
              <strong>Navigation</strong>
            </a>
            <a class="nav-link my-1" href="#records">
              <strong>Records</strong>
            </a>
            <nav class="nav nav-pills flex-column">
              <a class="nav-link ml-3 my-1" href="#new-record">Creating a new record</a>
              <a class="nav-link ml-3 my-1" href="#manage-record">Managing existing records</a>
            </nav>
            <a class="nav-link my-1" href="#collections">
              <strong>Collections</strong>
            </a>
            <nav class="nav nav-pills flex-column">
              <a class="nav-link ml-3 my-1" href="#new-collection">Creating a new collection</a>
              <a class="nav-link ml-3 my-1" href="#manage-collection">Managing existing collections</a>
            </nav>
            <a class="nav-link my-1" href="#groups">
              <strong>Groups</strong>
            </a>
            <nav class="nav nav-pills flex-column">
              <a class="nav-link ml-3 my-1" href="#new-group">Creating a new group</a>
              <a class="nav-link ml-3 my-1" href="#manage-group">Managing existing groups</a>
            </nav>
            <a class="nav-link my-1" href="#templates">
              <strong>Templates</strong>
            </a>
            <nav class="nav nav-pills flex-column">
              <a class="nav-link ml-3 my-1" href="#new-template">Creating a new template</a>
              <a class="nav-link ml-3 my-1" href="#manage-template">Managing existing templates</a>
            </nav>
            <a class="nav-link my-1" href="#settings">
              <strong>Settings</strong>
            </a>

            {{ template_hook("kadi_template_help_nav_after") }}
          </nav>
        </nav>
      </div>

      <div class="col-12 col-lg-8 col-xl-9">
        <div class="overflow-auto" data-spy="scroll" data-target="#help-navbar" data-offset="20" style="height: 75vh;">
          <div class="mx-3 mt-3 ml-lg-0">
            {{ template_hook("kadi_template_help_content_before") }}

            {% include "main/snippets/help/login.html" %}
            <hr>
            {% include "main/snippets/help/navigation.html" %}
            <hr>
            {% include "main/snippets/help/records.html" %}
            <hr>
            {% include "main/snippets/help/collections.html" %}
            <hr>
            {% include "main/snippets/help/groups.html" %}
            <hr>
            {% include "main/snippets/help/templates.html" %}
            <hr>
            {% include "main/snippets/help/settings.html" %}

            {{ template_hook("kadi_template_help_content_after") }}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/home.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content %}
  {{ template_hook("kadi_template_home_before") }}

  <div class="card-deck mb-4">
    <div class="card">
      <div class="card-header bg-primary text-white">
        <h5 class="mt-2">{% trans %}Welcome to{% endtrans %} <strong>Kadi4Mat</strong></h5>
      </div>
      <div class="card-body">
        {% trans %}You are currently logged in as{% endtrans %}
        <identity-popover :user="{{ json_user(current_user) }}"></identity-popover>.
      </div>
    </div>
    <div class="card">
      <div class="card-body d-flex align-items-center">
        <div class="w-100">
          <a href="{{ url_for('main.about') }}" class="btn btn-block btn-primary">
            {% trans %}About{% endtrans %} Kadi4Mat
          </a>
          <a href="{{ url_for('main.help') }}" class="btn btn-block btn-primary">
            <i class="fas fa-question-circle"></i> {% trans %}Help{% endtrans %}
          </a>
        </div>
      </div>
    </div>
  </div>
  <h4>
    <strong class="text-primary">{% trans %}Latest updates{% endtrans %}</strong>
  </h4>
  {% if len(latest_updates) > 0 %}
    {% set num_cards = len(latest_updates) if len(latest_updates) % 2 == 0 else len(latest_updates) + 1 %}

    {% for index in range(num_cards) %}
      {% if index % 2 == 0 %}
        <div class="card-deck {% if index < num_cards - 2 %}mb-4{% endif %}">
      {% endif %}
          <div class="card card-action {% if index >= len(latest_updates) %}border-0{% endif %}">
            {% if index < len(latest_updates) %}
              {% set resource = latest_updates[index] %}

              <div class="card-body pb-0">
                <a href="{{ url_for(resource.endpoint, id=resource.id) }}" class="stretched-link">
                  <span class="badge badge-light border border-muted font-weight-normal mb-2 mb-xl-0 float-xl-right">
                    {{ resource.type | capitalize }}
                  </span>
                  <p>
                    <small>{% snippet "resources/visibility", resource=resource %}</small>
                    <strong>{{ resource.title }}</strong>
                    <br>
                    @{{ resource.identifier }}
                  </p>
                  <p>
                    {% if resource.plain_description %}
                      <span class="text-muted">{{ resource.plain_description | truncate(200, True) }}</span>
                    {% else %}
                      <em class="text-muted">{% trans %}No description.{% endtrans %}</em>
                    {% endif %}
                  </p>
                </a>
              </div>
              <div class="card-footer bg-white py-1">
                <small class="text-muted">
                  {% trans %}Last modified{% endtrans %} <from-now timestamp="{{ resource.last_modified }}"></from-now>
                </small>
              </div>
            {% endif %}
          </div>
      {% if index % 2 == 1 %}
        </div>
      {% endif %}
    {% endfor %}
  {% else %}
    <em class="text-muted">{% trans %}None yet.{% endtrans %}</em>
  {% endif %}
  <br>
  {% if len(groups) > 0 %}
    <div class="d-flex justify-content-between">
      <h4>
        <strong class="text-primary">{% trans %}My groups{% endtrans %}</strong>
      </h4>

      {% if has_more_groups %}
        <div>
          <a href="{{ url_for('accounts.view_resources', id=current_user.id, tab='groups') }}">
            {% trans %}View all{% endtrans %}
          </a>
        </div>
      {% endif %}
    </div>

    {% set num_cards = len(groups) if len(groups) % 2 == 0 else len(groups) + 1 %}

    {% for index in range(num_cards) %}
      {% if index % 2 == 0 %}
        <div class="card-deck {% if index < num_cards - 2 %}mb-4{% endif %}">
      {% endif %}
          <div class="card card-action {% if index >= len(groups) %}border-0{% endif %}">
            {% if index < len(groups) %}
              {% set group = groups[index] %}
              <div class="card-body">
                <a href="{{ url_for('groups.view_group', id=group.id) }}" class="stretched-link">
                  {% if group.image_name %}
                    <img class="img-thumbnail float-xl-right ml-0 ml-2 mb-4 mb-xl-0"
                         width="100"
                         src="{{ url_for('api.preview_group_image', id=group.id,
                                         ts=group.last_modified | timestamp) }}">
                  {% endif %}

                  <p>
                    <small>{% snippet "resources/visibility", resource=group %}</small>
                    <strong>{{ group.title }}</strong>
                    <br>
                    @{{ group.identifier }}
                  </p>

                  {% if group.plain_description %}
                    <span class="text-muted">{{ group.plain_description | truncate(200, True) }}</span>
                  {% else %}
                    <em class="text-muted">{% trans %}No description.{% endtrans %}</em>
                  {% endif %}
                </a>
              </div>
              <div class="card-footer bg-white py-1">
                <small class="text-muted">
                  {% trans %}Last modified{% endtrans %} <from-now timestamp="{{ group.last_modified }}"></from-now>
                </small>
              </div>
            {% endif %}
          </div>
      {% if index % 2 == 1 %}
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}
{% endblock %}

kadi/modules/main/templates/main/index.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content_wrapper %}
  {{ template_hook("kadi_template_index_before") }}

  <div class="card bg-primary text-white">
    <div class="row align-items-center">
      <div class="col-lg-8 d-none d-lg-block">
        <img class="img-fluid" width="650" src="{{ static_url('images/kadi_bg.png') }}">
      </div>
      <div class="col-lg-4 m-3 m-lg-0 text-center text-lg-left">
        <div>
          <h4>
            <strong>{% trans %}Karlsruhe Data Infrastructure{% endtrans %}</strong>
          </h4>
          <h5>{% trans %}for Materials Science{% endtrans %}</h5>
        </div>
      </div>
    </div>
  </div>
  <div class="card mt-4">
    <div class="card-body my-3">
      <div class="row align-items-center">
        <div class="col-lg-8 px-5">
          {% trans %}Welcome to{% endtrans %} <strong>Kadi4Mat</strong>.
          {% trans trimmed %}
            Kadi4Mat is the <strong>Karlsruhe Data Infrastructure for Materials Science</strong>, a software for
            managing research data with the aim of combining new concepts with established technologies and existing
            solutions.
          {% endtrans %}
        </div>
        <div class="col-lg-4 mt-3 mt-lg-0">
          <a href="{{ url_for('main.about') }}" class="btn btn-block btn-light">
            {% trans %}About{% endtrans %} Kadi4Mat
          </a>
          <a href="{{ url_for('main.help') }}" class="btn btn-block btn-light">
            <i class="fas fa-question-circle"></i> {% trans %}Help{% endtrans %}
          </a>
        </div>
      </div>
    </div>
    <div class="card-footer py-3">
      <div class="row justify-content-end">
        <div class="col-lg-4">
          <a href="{{ url_for('accounts.login') }}" class="btn btn-block btn-primary">
            <i class="fas fa-sign-in-alt"></i> {% trans %}Login{% endtrans %}
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/snippets/help/collections.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

<h4 id="collections">Collections</h4>
<p>
  Collections represent simple, logical groupings of multiple records.
</p>
<h5 id="new-collection">Creating a new collection</h5>
<p>
  Creating a new collection is very similar to <a href="#new-record"><strong>creating a new record</strong></a>, except
  that only some basic metadata is necessary. Similarly, no files can be uploaded. Instead, the application will
  redirect to the overview of the collection right away.
</p>
<h5 id="manage-collection">Managing existing collections</h5>
<p>
  Similar to records, collections have their own navigation menu, offering different views for linking resources,
  managing access permissions, editing metadata and viewing revisions. As the menu items are very similar to those of
  records, please refer to <a href="#manage-record"><strong>managing existing records</strong></a> for more information.
</p>

kadi/modules/main/templates/main/snippets/help/groups.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

<h4 id="groups">Groups</h4>
<p>
  Groups can be used to group several users together, allowing for easier access management.
</p>
<h5 id="new-group">Creating a new group</h5>
<p>
  Creating a new group is again very similar to <a href="#new-record"><strong>creating a new record</strong></a> or
  <a href="#new-collection"><strong>creating a new collection</strong></a>. Aside from basic metadata, a group picture
  can also be uploaded, which will be shown on the group overview as well as on search result pages.
</p>
<h5 id="manage-group">Managing existing groups</h5>
<p>
  The management of existing groups is similar to
  <a href="#manage-record"><strong>managing existing records</strong></a> or
  <a href="#manage-collection"><strong>managing existing collections</strong></a> as well. The main difference is that
  instead of having a view for managing access permissions, there is a view for managing the members of the group:
</p>
<dl class="row">
  <dt class="col-md-2">Manage members</dt>
  <dd class="col-md-10">
    Managing the members of a group is comparable to managing the access permissions of records or collections, as group
    membership is linked to the access permissions of a group. Specifically, as long as a user has any role in a group,
    he is effectively a member of this group as well, while of course also having the respective permissions his role
    provides.
  </dd>
</dl>

kadi/modules/main/templates/main/snippets/help/navigation.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

<h4 id="navigation">Navigation</h4>
<p>
  After logging in, the navigation in the top left allows access to
  <a href="#records"><strong>Records</strong></a>, <a href="#collections"><strong>Collections</strong></a>,
  <a href="#groups"><strong>Groups</strong></a> and <a href="#templates"><strong>Templates</strong></a>.
  Each navigation item leads to the respective main page of these resources, where new resources can be created and
  existing ones can be searched for. Details about those resources are described in the following sections. The
  navigation also provides quick access to create new resources or search for existing ones. Furthermore, the dropdown
  menu on the far right can be used to access the user profile, created resources as well as the
  <a href="#settings"><strong>Settings</strong></a>.
</p>